services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: personsapiuser
      POSTGRES_PASSWORD: MLkKMBt1Gz;Jw9gv
      POSTGRES_DB: persons
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10